services:
  parser:
    build:
      context: ./parser
    container_name: parser
    restart: unless-stopped
    env_file:
      - ./parser/.env
    volumes:
      - ./logs:/logs
      - ./mail/inbox:/mail/inbox:Z
    networks:
      - smtphook

networks:
  smtphook:
